/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectonn;

import java.awt.Color;
import java.text.NumberFormat;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author Uriel
 */
public class MatrixFrame extends javax.swing.JFrame {

    /**
     * Creates new form DigitalFrame
     */
    Network network;
    double DisplayData[][]= new double[1][35];
    JButton botones[][] = new JButton[7][5];
    public MatrixFrame() {
        initComponents();
        cargarbotones();
        JFrame.setDefaultLookAndFeelDecorated(false);
       // SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MistAquaSkin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelsalida1 = new javax.swing.JLabel();
        labelsalida2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelsalida3 = new javax.swing.JLabel();
        labelsalida4 = new javax.swing.JLabel();
        textosalida1 = new javax.swing.JTextField();
        textosalida3 = new javax.swing.JTextField();
        textosalida2 = new javax.swing.JTextField();
        textosalida4 = new javax.swing.JTextField();
        labelepocas = new javax.swing.JLabel();
        labelneuronas = new javax.swing.JLabel();
        labelerrormin = new javax.swing.JLabel();
        labeltasa = new javax.swing.JLabel();
        textoepocas = new javax.swing.JTextField();
        textoneuronas = new javax.swing.JTextField();
        textoerrormin = new javax.swing.JTextField();
        textotasas = new javax.swing.JTextField();
        botonentrenas = new javax.swing.JButton();
        botonevaluar = new javax.swing.JButton();
        botonlimpiar = new javax.swing.JButton();
        panelmatrix = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Redes Neuronales");

        labelsalida1.setText("S1");

        labelsalida2.setText("S2");

        labelsalida3.setText("S3");

        labelsalida4.setText("S4");

        labelepocas.setText("Epocas");

        labelneuronas.setText("Neuronas");

        labelerrormin.setText("Error Minimo");

        labeltasa.setText("Tasa");

        botonentrenas.setText("Entrenar");
        botonentrenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonentrenasActionPerformed(evt);
            }
        });

        botonevaluar.setText("Evaluar");
        botonevaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonevaluarActionPerformed(evt);
            }
        });

        botonlimpiar.setText("Limpiar");
        botonlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelmatrixLayout = new javax.swing.GroupLayout(panelmatrix);
        panelmatrix.setLayout(panelmatrixLayout);
        panelmatrixLayout.setHorizontalGroup(
            panelmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        panelmatrixLayout.setVerticalGroup(
            panelmatrixLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelmatrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labeltasa)
                            .addComponent(labelepocas)
                            .addComponent(labelerrormin)
                            .addComponent(labelneuronas))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoerrormin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoneuronas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textotasas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoepocas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelsalida1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelsalida2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelsalida3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelsalida4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textosalida2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(textosalida3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textosalida4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textosalida1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonentrenas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonevaluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(botonlimpiar)
                        .addGap(258, 258, 258))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textosalida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelsalida1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelsalida2)
                            .addComponent(textosalida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelsalida3)
                            .addComponent(textosalida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelsalida4)
                            .addComponent(textosalida4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonentrenas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonevaluar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoepocas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelepocas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoneuronas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelneuronas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelerrormin)
                    .addComponent(textoerrormin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textotasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeltasa))
                .addGap(18, 18, 18)
                .addComponent(botonlimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(panelmatrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonentrenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonentrenasActionPerformed
     network=new Network(35,Integer.parseInt(textoneuronas.getText()),8,Double.parseDouble(textotasas.getText()),Double.parseDouble(textoerrormin.getText()));  
     double DisplayInput[][] =
  {
   {1.0,1.0,1.0,1.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,1.0,1.0,1.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0},//A
  
   {1.0,1.0,1.0,1.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,1.0,1.0,1.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0},//B
         
   {1.0,1.0,1.0,1.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,1.0,1.0,1.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0},//C
    
   {1.0,1.0,1.0,1.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,1.0,1.0,1.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0},//D
          
   {1.0,1.0,1.0,1.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,1.0,1.0,1.0,1.0,
    1.0,0.0,0.0,0.0,1.0,
    1.0,0.0,0.0,0.0,1.0},//E
    
    
    
    
   
   /*{0.0,1.0,1.0,0.0,0.0,0.0,0.0},//1
   {1.0,1.0,0.0,1.0,1.0,0.0,1.0},//2
   {1.0,1.0,1.0,1.0,0.0,0.0,1.0},//3
   {0.0,1.0,1.0,0.0,0.0,1.0,1.0},//4
   {1.0,0.0,1.0,1.0,0.0,1.0,1.0},//5
   {1.0,0.0,1.0,1.0,1.0,1.0,1.0},//6
   {1.0,1.0,1.0,0.0,0.0,0.0,0.0},//7
   {1.0,1.0,1.0,1.0,1.0,1.0,1.0},//8
   {1.0,1.0,1.0,1.0,0.0,1.0,1.0},//9
   {1.0,1.0,1.0,0.0,1.0,1.0,1.0},//A
   {0.0,0.0,1.0,1.0,1.0,1.0,1.0},//B
   {1.0,0.0,0.0,1.0,1.0,1.0,0.0},//C
   {0.0,1.0,1.0,1.0,1.0,1.0,1.0},//D
   {1.0,0.0,0.0,1.0,1.0,1.0,1.0},//E
   {1.0,0.0,0.0,0.0,1.0,1.0,1.0} //F*/
  };

  double DisplayIdeal[][] =
  { 
    {0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0},
    /*{0.0,0.0,0.0,1.0},
    {0.0,0.0,1.0,0.0},
    {0.0,0.0,1.0,1.0},
    {0.0,1.0,0.0,0.0},
    {0.0,1.0,0.0,1.0},
    {0.0,1.0,1.0,0.0},
    {0.0,1.0,1.0,1.0},
    {1.0,0.0,0.0,0.0},
    {1.0,0.0,0.0,1.0},
    {1.0,0.0,1.0,0.0},
    {1.0,0.0,1.0,1.0},
    {1.0,1.0,0.0,0.0},
    {1.0,1.0,0.0,1.0},
    {1.0,1.0,1.0,0.0},
    {1.0,1.0,1.0,1.0}*/
    };
  
   for (int i=0;i<Integer.parseInt(textoepocas.getText());i++) {
   for (int j=0;j<DisplayInput.length;j++) {
       //System.out.println(DisplayInput[15][2]);
       network.computeOutputs(DisplayInput[j]);
       network.calcError(DisplayIdeal[j]);
       //System.out.println(DisplayIdeal[15]);
       network.learn();
   }
    NumberFormat percentFormat = NumberFormat.getPercentInstance();
  percentFormat.setMinimumFractionDigits(4);
   System.out.println( "Prueba #" + i + ",Error:" +
             percentFormat.format(network.getError(DisplayInput.length)) );
  }

   System.out.println("Llamada:");

  for (int i=0;i<DisplayInput.length;i++) {

   for (int j=0;j<DisplayInput[0].length;j++) {
    System.out.print( DisplayInput[i][j] +":" );
   }

   double out[] = network.computeOutputs(DisplayInput[i]);
   System.out.println("="+out[4]);
   System.out.println("="+out[5]);
   System.out.println("="+out[6]);
   System.out.println("="+out[7]);
  }
    }//GEN-LAST:event_botonentrenasActionPerformed

    private void botonevaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonevaluarActionPerformed
   /*      double xorData[][] = getGrid();
    int update=0;

    for (int i=0;i<4;i++) {
      NumberFormat nf = NumberFormat.getInstance();
      double d[] = network.computeOutputs(xorData[i]);
      data[i][3].setText(nf.format(d[0]));*/
        
        // TODO add your handling code here:
      int k=0; 
       for(int i=0;i<7;i++)
       {
           for(int j=0;j<5;j++)
           {
               if(botones[i][j].getBackground()==Color.red){
                  DisplayData[0][k]=1.0;
               }
               k++;
           }
       }
      
        
        
      double d[] = network.computeOutputs(DisplayData[0]);
      textosalida1.setText(String.valueOf(d[4]));
      textosalida2.setText(String.valueOf(d[5]));
      textosalida3.setText(String.valueOf(d[6]));
      textosalida4.setText(String.valueOf(d[7]));
      
    }//GEN-LAST:event_botonevaluarActionPerformed

    private void botonlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonlimpiarActionPerformed
       
       for(int i=0;i<7;i++){
         for(int j=0;j<5;j++){
             botones[i][j].setBackground(Color.white);
             botones[i][j].setOpaque(true);
             botones[i][j].setContentAreaFilled(true);
         }
       }
        
        for(int i=0;i<35;i++){
            DisplayData[0][i]=0.0;
        }
        
    }//GEN-LAST:event_botonlimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatrixFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatrixFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatrixFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatrixFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatrixFrame().setVisible(true);
            }
        });
    }
    
    public void cargarbotones() {
        ImageIcon imagen;
        int x = 0;
        int y = 0;
        for (int i = 0; i < 7; i++) {
            for (int j = 0; j < 5; j++) {

                botones[i][j] = new JButton();
                botones[i][j].setBounds(x, y, 40, 40);
               // botones[i][j].setBackground(Color.red);
                botones[i][j].setBackground(Color.white);
                botones[i][j].setOpaque(true);
                botones[i][j].setContentAreaFilled(true);

                 botones[i][j].addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        MatrixActionPerformed(evt);
                    }
                });
                panelmatrix.add(botones[i][j]);
                x = x + 40;
                if (j == 4) {
                    x = 0;
                }
            }
            y = y + 40;
        }

    }
    
     public void MatrixActionPerformed(java.awt.event.ActionEvent evt) {
       for (int i = 0; i < 7; i++) {
                    for (int j = 0; j < 5; j++) {
                        if (botones[i][j] == evt.getSource()) {
                            System.out.print("entre");
                            botones[i][j].setBackground(Color.red);
                            botones[i][j].setContentAreaFilled(true);
                            botones[i][j].setOpaque(true);
                            
                        }
                    }
       }
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonentrenas;
    private javax.swing.JButton botonevaluar;
    private javax.swing.JButton botonlimpiar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelepocas;
    private javax.swing.JLabel labelerrormin;
    private javax.swing.JLabel labelneuronas;
    private javax.swing.JLabel labelsalida1;
    private javax.swing.JLabel labelsalida2;
    private javax.swing.JLabel labelsalida3;
    private javax.swing.JLabel labelsalida4;
    private javax.swing.JLabel labeltasa;
    private javax.swing.JPanel panelmatrix;
    private javax.swing.JTextField textoepocas;
    private javax.swing.JTextField textoerrormin;
    private javax.swing.JTextField textoneuronas;
    private javax.swing.JTextField textosalida1;
    private javax.swing.JTextField textosalida2;
    private javax.swing.JTextField textosalida3;
    private javax.swing.JTextField textosalida4;
    private javax.swing.JTextField textotasas;
    // End of variables declaration//GEN-END:variables
}
