/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectonn;

import java.awt.Color;
import java.text.NumberFormat;
import javax.swing.JFrame;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author Uriel
 */
public class DigitalFrame extends javax.swing.JFrame {

    /**
     * Creates new form DigitalFrame
     */
    Network network;
    double DisplayData[][]= new double[1][7];
    public DigitalFrame() {
        initComponents();
        A.setBackground(Color.white);
        A.setOpaque(true);
        B.setBackground(Color.white);
        B.setOpaque(true);
        C.setBackground(Color.white);
        C.setOpaque(true);
        D.setBackground(Color.white);
        D.setOpaque(true);
        E.setBackground(Color.white);
        E.setOpaque(true);
        F.setBackground(Color.white);
        F.setOpaque(true);
        G.setBackground(Color.white);
        G.setOpaque(true);
        JFrame.setDefaultLookAndFeelDecorated(false);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MistAquaSkin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        F = new javax.swing.JLabel();
        E = new javax.swing.JLabel();
        G = new javax.swing.JLabel();
        labelsalida1 = new javax.swing.JLabel();
        labelsalida2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelsalida3 = new javax.swing.JLabel();
        labelsalida4 = new javax.swing.JLabel();
        textosalida1 = new javax.swing.JTextField();
        textosalida3 = new javax.swing.JTextField();
        textosalida2 = new javax.swing.JTextField();
        textosalida4 = new javax.swing.JTextField();
        labelepocas = new javax.swing.JLabel();
        labelneuronas = new javax.swing.JLabel();
        labelerrormin = new javax.swing.JLabel();
        labeltasa = new javax.swing.JLabel();
        textoepocas = new javax.swing.JTextField();
        textoneuronas = new javax.swing.JTextField();
        textoerrormin = new javax.swing.JTextField();
        textotasas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        botonentrenas = new javax.swing.JButton();
        botonevaluar = new javax.swing.JButton();
        botonlimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Redes Neuronales");

        A.setBackground(new java.awt.Color(255, 255, 255));
        A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AMouseClicked(evt);
            }
        });

        B.setBackground(new java.awt.Color(255, 255, 255));
        B.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BMouseClicked(evt);
            }
        });

        C.setBackground(new java.awt.Color(255, 255, 255));
        C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CMouseClicked(evt);
            }
        });

        D.setBackground(new java.awt.Color(255, 255, 255));
        D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DMouseClicked(evt);
            }
        });

        F.setBackground(new java.awt.Color(255, 255, 255));
        F.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FMouseClicked(evt);
            }
        });

        E.setBackground(new java.awt.Color(255, 255, 255));
        E.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EMouseClicked(evt);
            }
        });

        G.setBackground(new java.awt.Color(255, 255, 255));
        G.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GMouseClicked(evt);
            }
        });

        labelsalida1.setText("S1");

        labelsalida2.setText("S2");

        labelsalida3.setText("S3");

        labelsalida4.setText("S4");

        labelepocas.setText("Epocas");

        labelneuronas.setText("Neuronas");

        labelerrormin.setText("Error Minimo");

        labeltasa.setText("Tasa");

        jLabel10.setText("Cargando...");

        botonentrenas.setText("Entrenar");
        botonentrenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonentrenasActionPerformed(evt);
            }
        });

        botonevaluar.setText("Evaluar");
        botonevaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonevaluarActionPerformed(evt);
            }
        });

        botonlimpiar.setText("Limpiar");
        botonlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(botonlimpiar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelerrormin)
                                    .addComponent(labeltasa)
                                    .addComponent(labelepocas)
                                    .addComponent(labelneuronas))
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoepocas, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(textoneuronas)
                                    .addComponent(textoerrormin)
                                    .addComponent(textotasas))
                                .addContainerGap(78, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelsalida2)
                                            .addComponent(labelsalida3)
                                            .addComponent(labelsalida4))
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textosalida3)
                                            .addComponent(textosalida4)
                                            .addComponent(textosalida2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelsalida1)
                                        .addGap(35, 35, 35)
                                        .addComponent(textosalida1)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonentrenas, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonevaluar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textosalida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelsalida1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelsalida2)
                                    .addComponent(textosalida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelsalida3)
                                    .addComponent(textosalida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelsalida4)
                                    .addComponent(textosalida4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botonentrenas, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonevaluar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textoepocas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelepocas))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textoneuronas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelneuronas))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelerrormin)
                                .addComponent(textoerrormin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textotasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labeltasa)
                                .addComponent(botonlimpiar))
                            .addGap(39, 39, 39))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(C, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(D, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(0, 105, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(E, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonentrenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonentrenasActionPerformed
     network=new Network(7,Integer.parseInt(textoneuronas.getText()),4,Double.parseDouble(textotasas.getText()),Double.parseDouble(textoerrormin.getText()));  
     double DisplayInput[][] =
  {
   {1.0,1.0,1.0,1.0,1.0,1.0,0.0},//0
   {0.0,1.0,1.0,0.0,0.0,0.0,0.0},//1
   {1.0,1.0,0.0,1.0,1.0,0.0,1.0},//2
   {1.0,1.0,1.0,1.0,0.0,0.0,1.0},//3
   {0.0,1.0,1.0,0.0,0.0,1.0,1.0},//4
   {1.0,0.0,1.0,1.0,0.0,1.0,1.0},//5
   {1.0,0.0,1.0,1.0,1.0,1.0,1.0},//6
   {1.0,1.0,1.0,0.0,0.0,0.0,0.0},//7
   {1.0,1.0,1.0,1.0,1.0,1.0,1.0},//8
   {1.0,1.0,1.0,1.0,0.0,1.0,1.0},//9
   {1.0,1.0,1.0,0.0,1.0,1.0,1.0},//A
   {0.0,0.0,1.0,1.0,1.0,1.0,1.0},//B
   {1.0,0.0,0.0,1.0,1.0,1.0,0.0},//C
   {0.0,1.0,1.0,1.0,1.0,1.0,1.0},//D
   {1.0,0.0,0.0,1.0,1.0,1.0,1.0},//E
   {1.0,0.0,0.0,0.0,1.0,1.0,1.0} //F
  };

  double DisplayIdeal[][] =
  { 
    {0.0,0.0,0.0,0.0},
    {0.0,0.0,0.0,1.0},
    {0.0,0.0,1.0,0.0},
    {0.0,0.0,1.0,1.0},
    {0.0,1.0,0.0,0.0},
    {0.0,1.0,0.0,1.0},
    {0.0,1.0,1.0,0.0},
    {0.0,1.0,1.0,1.0},
    {1.0,0.0,0.0,0.0},
    {1.0,0.0,0.0,1.0},
    {1.0,0.0,1.0,0.0},
    {1.0,0.0,1.0,1.0},
    {1.0,1.0,0.0,0.0},
    {1.0,1.0,0.0,1.0},
    {1.0,1.0,1.0,0.0},
    {1.0,1.0,1.0,1.0}
    };
  
   for (int i=0;i<Integer.parseInt(textoepocas.getText());i++) {
   for (int j=0;j<DisplayInput.length;j++) {
       //System.out.println(DisplayInput[15][2]);
       network.computeOutputs(DisplayInput[j]);
       network.calcError(DisplayIdeal[j]);
       //System.out.println(DisplayIdeal[15]);
       network.learn();
   }
    NumberFormat percentFormat = NumberFormat.getPercentInstance();
  percentFormat.setMinimumFractionDigits(4);
   System.out.println( "Prueba #" + i + ",Error:" +
             percentFormat.format(network.getError(DisplayInput.length)) );
  }

   System.out.println("Llamada:");

  for (int i=0;i<DisplayInput.length;i++) {

   for (int j=0;j<DisplayInput[0].length;j++) {
    System.out.print( DisplayInput[i][j] +":" );
   }

   double out[] = network.computeOutputs(DisplayInput[i]);
   System.out.println("="+out[0]);
   System.out.println("="+out[1]);
   System.out.println("="+out[2]);
   System.out.println("="+out[3]);
  }
    }//GEN-LAST:event_botonentrenasActionPerformed

    private void botonevaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonevaluarActionPerformed
   /*      double xorData[][] = getGrid();
    int update=0;

    for (int i=0;i<4;i++) {
      NumberFormat nf = NumberFormat.getInstance();
      double d[] = network.computeOutputs(xorData[i]);
      data[i][3].setText(nf.format(d[0]));*/
        
        // TODO add your handling code here:
     
      
        if (A.getBackground() == Color.red) DisplayData[0][0]=1.0;
        if (B.getBackground() == Color.red) DisplayData[0][1]=1.0;
        if (C.getBackground() == Color.red) DisplayData[0][2]=1.0;
        if (D.getBackground() == Color.red) DisplayData[0][3]=1.0;
        if (E.getBackground() == Color.red) DisplayData[0][4]=1.0;
        if (F.getBackground() == Color.red) DisplayData[0][5]=1.0;
        if (G.getBackground() == Color.red) DisplayData[0][6]=1.0;
        
      double d[] = network.computeOutputs(DisplayData[0]);
      textosalida1.setText(String.valueOf(d[0]));
      textosalida2.setText(String.valueOf(d[1]));
      textosalida3.setText(String.valueOf(d[2]));
      textosalida4.setText(String.valueOf(d[3]));
      
    }//GEN-LAST:event_botonevaluarActionPerformed

    private void AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AMouseClicked
        A.setBackground(Color.red);
       // System.out.println("huevos");
    }//GEN-LAST:event_AMouseClicked

    private void BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMouseClicked
       B.setBackground(Color.red); 
     
       // TODO add your handling code here:
    }//GEN-LAST:event_BMouseClicked

    private void GMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GMouseClicked
     G.setBackground(Color.red);  
     // TODO add your handling code here:
    }//GEN-LAST:event_GMouseClicked

    private void CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMouseClicked
      C.setBackground(Color.red); 
      // TODO add your handling code here:
    }//GEN-LAST:event_CMouseClicked

    private void DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DMouseClicked
       D.setBackground(Color.red);
      // TODO add your handling code here:
    }//GEN-LAST:event_DMouseClicked

    private void EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EMouseClicked
      E.setBackground(Color.red); 
      // TODO add your handling code here:
    }//GEN-LAST:event_EMouseClicked

    private void FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FMouseClicked
      F.setBackground(Color.red);
      // TODO add your handling code here:
    }//GEN-LAST:event_FMouseClicked

    private void botonlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonlimpiarActionPerformed
        A.setBackground(Color.white);
        B.setBackground(Color.white);
        C.setBackground(Color.white);
        D.setBackground(Color.white);
        E.setBackground(Color.white);
        F.setBackground(Color.white);
        G.setBackground(Color.white);
        
        
        for(int i=0;i<7;i++){
            DisplayData[0][i]=0.0;
        }
        
    }//GEN-LAST:event_botonlimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DigitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DigitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DigitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DigitalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DigitalFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel C;
    private javax.swing.JLabel D;
    private javax.swing.JLabel E;
    private javax.swing.JLabel F;
    private javax.swing.JLabel G;
    private javax.swing.JButton botonentrenas;
    private javax.swing.JButton botonevaluar;
    private javax.swing.JButton botonlimpiar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelepocas;
    private javax.swing.JLabel labelerrormin;
    private javax.swing.JLabel labelneuronas;
    private javax.swing.JLabel labelsalida1;
    private javax.swing.JLabel labelsalida2;
    private javax.swing.JLabel labelsalida3;
    private javax.swing.JLabel labelsalida4;
    private javax.swing.JLabel labeltasa;
    private javax.swing.JTextField textoepocas;
    private javax.swing.JTextField textoerrormin;
    private javax.swing.JTextField textoneuronas;
    private javax.swing.JTextField textosalida1;
    private javax.swing.JTextField textosalida2;
    private javax.swing.JTextField textosalida3;
    private javax.swing.JTextField textosalida4;
    private javax.swing.JTextField textotasas;
    // End of variables declaration//GEN-END:variables
}
